### ISSUE TITLE
v1.0.3 does not work with feign-core 10.x.x

### ISSUE THREAD

**Issue by karlmuscat** [OpenFeign/feign-annotation-error-decoder#11] opened 2019-02-19 11:59 UTC
Upgraded my projects to JDK 11 and as a result I had to upgrade also the Spring Cloud dependencies to the `Greenwich.RELEASE`. The `Greenwich.RELEASE` upgrades the feign libraries to 10.1.0, however the `feign-annotation-error-decoder`, still uses 9.5.0. 

The `Response` class in the latest `feign-core` library introduced a check that is breaking the `ExceptionGenerator` in the `feign-annotation-error-decoder`

The check is:
`checkState(builder.request != null, "original request is required");`

and this is the broken code:

```
static {
        Map<String,Collection<String>> testHeaders = new HashMap<String, Collection<String>>();
        testHeaders.put("TestHeader", Arrays.asList("header-value"));

        TEST_RESPONSE = Response.builder()
            .status(500)
            .body((Response.Body) null)
            .headers(testHeaders)
            .build();
    }
```

**Comment by karlmuscat** [comment] 2019-02-19 14:51
The issue is replicable through your unit tests, if the parent version is bumped to `10.2.1`

Fix is a one-liner in the static block of `ExceptionGenerator`

**Comment by saintf** [comment] 2019-02-21 07:46
Nice! Thanks! Are you ok to make the change, I'll review it and we try to
push it out?

**Comment by karlmuscat** [comment] 2019-02-21 08:37
Sure. Just tell me where to commit

**Comment by saintf** [comment] 2019-02-26 20:42
The usual way to contribute is:
* Fork the repo to your own side
* Make the changes (and tests if necessary)
* Create a PR against the repo inside the OpenFeign org
* I'll review it, provide comments (if any - given your suggestion it might
be a simple one-liner)

I'll merge it if all good, and then hit the release button that will upload
it to maven Central - and job done :)

Does that sound fair?

**Comment by karlmuscat** [comment] 2019-02-27 09:28
Very :) PR done. Thanks.

**Comment by saintf** [comment] 2019-03-01 01:30
released with https://github.com/OpenFeign/feign-annotation-error-decoder/releases/tag/release-1.1.0 - should be in maven-central shortly. was compiled with openjdk8 (as opposed to oraclejdk8 - which is what I expected it to be compiled with - but... should still work. 1.1.1 will be compiled with oraclejdk8).

**Closed as completed by saintf** 2019-03-01 01:30 UTC

**Comment by karlmuscat** [comment] 2019-03-01 10:29
is it normal that it's still not visible by this time?

https://mvnrepository.com/artifact/io.github.openfeign/feign-annotation-error-decoder

**Comment by saintf** [comment] 2019-03-01 22:28
No... I looked for it. Turns out Travis cancelled the build that pushes it.
Since then, I've released a new version (1.1.1) and that didngo through and
should show up shortly.

Unfortunately... Due to a race condition, the first build was a Java 11
compiled build. If you pull it and it's java11 (and you need java8) let me
know - I'll release a 1.1.2 with Java 8 (I've removed the race at build
time issue... So it's always java8 that actually gets deployed/built/etc).

Thanks!

**Comment by saintf** [comment] 2019-03-01 23:24
@karlmuscat I just pushed 1.1.2 - compiled with java 8 (1.1.1 turns out, in maven central, is compiled with java 11 as I just confirmed). There's no difference between those two. It won't "show up" for a few hours in search results since those take time to get updated, but if you pull it into your project it should work now. Thanks, and sorry for the mess!

**Comment by RajeevRaparthi** [comment] 2020-01-03 14:00
First check your dependency by using mvn dependency:tree
Use the below dependency Management for spring-boot to download the suitable versions.

		<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

I am using Java 10, cloud.version is Finchley.SR2 and sprinb-boot:2.2.0 and spring-cloud-starter-openfeign :2.1.2.RELEASE. and this combination worked for me to fix the issue.
use inbuilt jars as wihtout version, so that cloud downloads working versions
	<dependency>
			
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-httpclient</artifactId>
		</dependency>

Acctual problem was 10.x.x feign-core  was not working only io.github.openfeign:feign-core:jar:9.7.0:compile was working
